# GitHub Actions para desplegar la app de backend en Azure Web App

name: Build and deploy Node.js app to Azure Web App - back-musical

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Cambiar al directorio del backend y ejecutar npm install, build y test
      - name: Install, build, and test backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      # Subir el artefacto para el trabajo de despliegue
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Descargar el artefacto desde el trabajo de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Iniciar sesión en Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Desplegar la app en Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'back-musical'  # Asegúrate de que coincida con el nombre de tu app en Azure
          slot-name: 'production'
          package: ./backend  # Especifica la ruta del backend
